name: Python Package

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Install pytest
        run: |
          pip install pytest
      - name: Test with pytest
        run: |
          pytest tests/
      - name: Build distribution
        run: |
          python setup.py sdist bdist_wheel
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: dist/*.whl  # Upload only wheel files

  deploy-ec2:
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /path/to/deployment/directory

            # Download the wheel file directly from artifacts
            wget https://github.com/${{ github.repository }}/actions/artifacts/${{ github.run_id }}/downloads/linux-build.whl

            # Install the wheel file
            pip install linux-build.whl
